// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Models;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Domain.Models.ConfirmacaoProjeto", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("ProjetoId");

                    b.ToTable("ConfirmacoesProjeto");
                });

            modelBuilder.Entity("TaskManager.Models.Notificacao", b =>
                {
                    b.Property<Guid>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensagem")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProjetoRelacionadoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TarefaRelacionadaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlAcao")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificacaoId");

                    b.HasIndex("ProjetoRelacionadoId");

                    b.HasIndex("TarefaRelacionadaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("TaskManager.Models.Projeto", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("TaskManager.Models.ProjetoUsuario", b =>
                {
                    b.Property<Guid>("ProjetoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Proprietario")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjetoUsuarioId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProjetosUsuarios");
                });

            modelBuilder.Entity("TaskManager.Models.Tarefa", b =>
                {
                    b.Property<Guid>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AtribuidaParaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CriadaPorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<double?>("HorasEstimadas")
                        .HasColumnType("double");

                    b.Property<double?>("HorasReais")
                        .HasColumnType("double");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("TarefaId");

                    b.HasIndex("AtribuidaParaId");

                    b.HasIndex("CriadaPorId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("TaskManager.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("PrimeiroNome")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UltimoNome")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UrlImagemPerfil")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TaskManager.Models.Notificacao", b =>
                {
                    b.HasOne("TaskManager.Models.Projeto", "ProjetoRelacionado")
                        .WithMany()
                        .HasForeignKey("ProjetoRelacionadoId");

                    b.HasOne("TaskManager.Models.Tarefa", "TarefaRelacionada")
                        .WithMany()
                        .HasForeignKey("TarefaRelacionadaId");

                    b.HasOne("TaskManager.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjetoRelacionado");

                    b.Navigation("TarefaRelacionada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskManager.Models.Projeto", b =>
                {
                    b.HasOne("TaskManager.Models.Usuario", "Usuario")
                        .WithMany("ProjetosCriados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskManager.Models.ProjetoUsuario", b =>
                {
                    b.HasOne("TaskManager.Models.Projeto", "Projeto")
                        .WithMany("ProjetosUsuarios")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Models.Usuario", "Usuario")
                        .WithMany("ProjetosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskManager.Models.Tarefa", b =>
                {
                    b.HasOne("TaskManager.Models.Usuario", "AtribuidaPara")
                        .WithMany("TarefasAtribuidas")
                        .HasForeignKey("AtribuidaParaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskManager.Models.Usuario", "CriadaPor")
                        .WithMany("TarefasCriadas")
                        .HasForeignKey("CriadaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManager.Models.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtribuidaPara");

                    b.Navigation("CriadaPor");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("TaskManager.Models.Projeto", b =>
                {
                    b.Navigation("ProjetosUsuarios");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("TaskManager.Models.Usuario", b =>
                {
                    b.Navigation("Notificacoes");

                    b.Navigation("ProjetosCriados");

                    b.Navigation("ProjetosUsuarios");

                    b.Navigation("TarefasAtribuidas");

                    b.Navigation("TarefasCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
